// <auto-generated />
namespace TobaccoStore.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartInclude : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartInclude));
        
        string IMigrationMetadata.Id
        {
            get { return "201709061524465_CartInclude"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
