// <auto-generated />
namespace TobaccoStore.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Price_to_ProductInfo_added_12_09 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Price_to_ProductInfo_added_12_09));
        
        string IMigrationMetadata.Id
        {
            get { return "201709121012477_Price_to_ProductInfo_added_12_09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
